spring:
# Database
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/s_m_s
    driver-class-name: com.mysql.cj.jdbc.Driver
# Hibernate
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hinernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
# Server
server:
  error:
    include-message: always
# to see the hibernate related quarries
logging:
  level: debug

# logging.level.org.hibernate.SQL = DEBUG